- name : check even or odd number
  hosts: local
  connection: local #it will not ask for username and password
  vars:
    given_number: 5
  tasks:
  - when: given_number % 2 == 0
    debug:
      msg: "give number: {{given_number}} number is even"
    name: is even


  - name: is odd  
    debug:
      msg: "give number: {{given_number}} number is odd"
    when: given_number % 2 != 0
