- name : check even or odd number
  hosts: local
  connection: local #it will not ask for username and password
  vars:
    given_number: 5
  tasks:
  - name: check even or odd number
    debug:
      msg: "The number is even"
    when: number % 2 == 0
  - name: check even or odd number
    debug:
      msg: "The number is odd"
    when: number % 2 != 0