- name: demo on filters
  hosts: local
  connection: local
  vars:
    topics: "Linux, Shell, Ansible, Terraform, AWS"
    tagMap:
      name: Ansible
      project:  Roboshop
      environment: Development
    tagslist: [
        {
            "key": "name",
            "value": "Ansible"
        },
        {
            "key": "project",
            "value": "Roboshop"
        },
        {
            "key": "environment",
            "value": "Development"
        }
    ]

  tasks:
  - name: convert string to list
    debug:
      msg: "Topics are: {{ topics.split(',') }}"

  - name: set default value
    debug:
      msg: "Hi {{ Greeting | default('Good Morning') }}"

  - name: convert map to list
    debug:
      msg: "{{ tagMap | dict2items }}"
    
  - name: convert list to map
    debug:
      msg: "{{ tagslist | items2dict }}"