- name: demo on filters
  hosts: local
  connection: local
  tasks:
    topics: "Linux, Shell, Ansible, Terraform, AWS"
  tasks:
    - name: convert string to list
      debug:
        msg: "Topics are: {{ topics.split(',') }}"