[frontend]
172.31.37.103 ;COURSE="Anisble for NODE-1" #these are individual host level variables
172.31.18.6    ;COURSE="Anisble for NODE-2"

[local]
localhost 

; local group vars
; [local:vars]
; COURSE= "Ansible"
; TRAINER= "Sivakumar"
; DURATION= "10HRS"

; [frontend:vars]
; COURSE= "Ansible"
; TRAINER= "Sivakumar"
; DURATION= "10HRS"
