[frontend]
172.31.35.93

[local]
localhost 

; local group vars
[local:vars]
COURSE: "Ansible"
TRAINER: "Sivakumar"
DURATION: "10HRS"

[frontend:vars]
COURSE: "Ansible"
TRAINER: "Sivakumar"
DURATION: "10HRS"
